using CMasters.Entities.Concrete;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace CMasters.DataAccess.Concrete;

public class ApplicationDbContext :IdentityDbContext<AppUser,AppRole,string>
{
    public const string _connectionName= "CMaster";
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
    {
        
    }
    public DbSet<Post> Posts => Set<Post>();
    public DbSet<Category> Categories => Set<Category>();
    public DbSet<UserRefreshToken> UserRefreshTokens => Set<UserRefreshToken>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Post>().HasData(
            new Post()
            {
                Id = "60bb0c20-1652-42bb-82d2-58efb10d442e",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount=5,
                PostCreatedTime=DateTime.Now,
                Title= "Lorem ipsum dolor sit amet,",
                ViewCount=10
            },
            new Post()
            {
                Id = "7177eedd-71d8-4aa7-85f6-caea03a2dd64",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            },
            new Post()
            {
                Id = "4450e437-4eb2-4e0f-91dc-4f8fa395d2e1",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            },
            new Post()
            {
                Id = "638edd84-e810-4073-b29c-125c549686d0",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            },
            new Post()
            {
                Id = "b75bf5b5-ff64-4357-8e2d-a6d125b495b8",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            },
            new Post()
            {
                Id = "3966aa75-a14a-4e56-96ba-20927c02fcdb",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            },
            new Post()
            {
                Id = "e8f058b1-8e17-4cd3-b744-c96ed7438004",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            },
            new Post()
            {
                Id = "55f9445a-7a11-4902-a234-7f5365d1cdce",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            },
            new Post()
            {
                Id = "4ee68c24-6ef3-4db2-b046-a666302c2d31",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            },
            new Post()
            {
                Id = "4d231662-288d-4c6f-b90a-f95afc9937e5",
                AppUserId = "8586f8e8-c39b-4a0b-9a1d-4f56855d98a0",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean luctus a mauris ac malesuada. In est mauris, feugiat eget accumsan vitae, mattis laoreet enim. Fusce condimentum viverra sem vitae tincidunt. Aenean malesuada fermentum lectus. Maecenas vel molestie tellus, a interdum purus. Proin eu nulla in enim varius consequat id a ligula. Suspendisse porttitor massa eget diam faucibus, eu blandit nibh lacinia. Pellentesque nec magna felis. Mauris et felis fringilla, feugiat turpis suscipit, pulvinar tellus. Nulla pharetra dignissim lorem. Sed lorem lacus, bibendum efficitur velit non, fermentum venenatis orci. Nam eget fringilla metus, id laoreet ex. Vestibulum consequat turpis non laoreet sollicitudin. Maecenas finibus gravida scelerisque. Aenean libero elit, iaculis et massa sed, laoreet dapibus tortor.\r\n\r\nDuis sodales posuere venenatis. Suspendisse potenti. Nunc rutrum erat sapien, eget auctor sem porta non. Nullam hendrerit ornare gravida. Sed non nisi nec sem tincidunt pretium sit amet eu augue. Ut ac felis a massa maximus mattis sit amet nec nisi. Suspendisse cursus pharetra nisl a euismod. Fusce lobortis odio libero. Quisque egestas tortor iaculis, venenatis urna vulputate, tristique mi. Phasellus quis risus ac metus mattis condimentum et a enim.\r\n\r\nVestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla pulvinar sapien tellus, vel rhoncus eros rutrum non. Donec feugiat auctor nulla eget venenatis. Pellentesque tristique, sapien nec sollicitudin tincidunt, leo leo interdum lacus, sit amet venenatis odio nibh quis libero. Pellentesque pharetra sem nisi, vitae cursus lorem volutpat non. In ut sollicitudin neque, a euismod est. Nulla dignissim sagittis interdum. Morbi et massa sed odio gravida luctus nec eu ipsum. Proin nec felis pretium, condimentum eros eu, consectetur enim.\r\n\r\nPhasellus sapien massa, varius et metus eu, lacinia bibendum justo. Sed non auctor ligula, nec congue enim. Ut auctor malesuada nunc, eget consequat lectus finibus et. Quisque quis eleifend risus. Sed semper sed enim sit amet tincidunt. Morbi quis augue sed diam malesuada pellentesque vitae id lectus. Proin id neque id sapien sollicitudin scelerisque quis sed neque. Integer nulla velit, egestas in quam eu, feugiat facilisis odio.\r\n\r\nNullam laoreet arcu vitae dui egestas finibus. Nulla massa libero, maximus ac lobortis blandit, auctor at lectus. Morbi vel massa sed sapien porta blandit nec sit amet ante. Suspendisse consectetur mauris venenatis efficitur lacinia. Morbi sit amet ullamcorper odio, ac laoreet sapien. Proin dapibus leo ipsum, eu ornare nisl tristique at. Quisque facilisis malesuada rutrum.",
                LikeCount = 5,
                PostCreatedTime = DateTime.Now,
                Title = "Lorem ipsum dolor sit amet,",
                ViewCount = 10
            });
        builder.ApplyConfigurationsFromAssembly(GetType().Assembly);
        base.OnModelCreating(builder);
    }
}
